services:
  web:
    image: ghcr.io/lucchmielowski/emojivoto-web:latest
    container_name: emojivoto-web
    environment:
      - WEB_PORT=8080
      - EMOJISVC_HOST=emoji-svc:8080
      - VOTINGSVC_HOST=voting-svc:8080
      - INDEX_BUNDLE=dist/index_bundle.js
    ports:
      - "8080:8080"
    depends_on:
      - voting-svc
      - emoji-svc
    restart: unless-stopped

  vote-bot:
    image: ghcr.io/lucchmielowski/emojivoto-web:latest
    container_name: emojivoto-vote-bot
    entrypoint: ["/usr/local/bin/emojivoto-vote-bot"]
    environment:
      - WEB_HOST=web:8080
    depends_on:
      - web
    restart: unless-stopped

  emoji-svc:
    image: ghcr.io/lucchmielowski/emojivoto-emoji-svc:latest
    container_name: emojivoto-emoji-svc
    environment:
      - GRPC_PORT=8080
    ports:
      - "8081:8080"
    restart: unless-stopped

  voting-svc:
    image: ghcr.io/lucchmielowski/emojivoto-voting-svc:latest
    container_name: emojivoto-voting-svc
    environment:
      - GRPC_PORT=8080
    ports:
      - "8082:8080"
    restart: unless-stopped

networks:
  default:
    name: emojivoto-network
